<?php

/**
 * @file
 * BxSlider integration.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function bxslider_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the bxslider module.
    case 'help.page.bxslider':
      $output = '';
      $output .= '<h3>' . t('About BxSlider') . '</h3>';
      $output .= '<p>' . t('Integration BxSlider with Field Formaters.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function bxslider_theme($existing, $type, $theme, $path) {
  return array(
    'bxslider' => array(
      'variables' => array(
        'items' => array(),
        'settings' => array(),
      ),
      'template' => 'bxslider',
    ),
    'bxslider_ths' => array(
      'variables' => array(
        'items' => array(),
        'thumbnail_items' => array(),
        'settings' => array(),
      ),
      'template' => 'bxslider_ths',
    ),
    'bxslider_colorbox' => array(
      'variables' => array(
        'slide_item' => array(),
        'settings' => array(),
      ),
    ),
  );
}

/**
 * Preprocess function.
 */
function template_preprocess_bxslider(&$variables) {
  foreach ($variables['items'] as $key => $item) {

    $variables['slides'][$key]['image'] = array(
    // '#theme' => 'image',.
      '#theme' => 'image_style',
      '#style_name' => $variables['settings']['image_style'],
    );

    if (($entity = $item->entity) && empty($item->uri)) {
      $variables['slides'][$key]['image']['#uri'] = $entity->getFileUri();
    }
    else {
      $variables['slides'][$key]['image']['#uri'] = $item->uri;
    }
  }
}

/**
 * Preprocess function.
 */
function template_preprocess_bxslider_ths(&$variables) {
  foreach ($variables['items'] as $key => $item) {
    $variables['slides'][$key]['image'] = array(
      '#theme' => 'image_style',
      '#style_name' => $variables['settings']['image_style'],
    );

    if (($entity = $item->entity) && empty($item->uri)) {
      $variables['slides'][$key]['image']['#uri'] = $entity->getFileUri();
    }
    else {
      $variables['slides'][$key]['image']['#uri'] = $item->uri;
    }
  }

  foreach ($variables['thumbnail_items'] as $key => $item) {
    $variables['thumbnails'][$key]['image'] = array(
      '#theme' => 'image_style',
      '#style_name' => $variables['settings']['thumbnail_slider']['thumbnail_style'],
    );

    if (($entity = $item->entity) && empty($item->uri)) {
      $variables['thumbnails'][$key]['image']['#uri'] = $entity->getFileUri();
    }
    else {
      $variables['thumbnails'][$key]['image']['#uri'] = $item->uri;
    }
  }

}
